title: "Simon Locke"
author: "Simon Locke"
description: "Mathematical physics and learning — PhD student at City University of New York Graduate Center"

# Use the GitHub Pages–approved version of Minima
remote_theme: "pages-themes/minima@v0.2.0"

show_excerpts: true

# Use the Solarized color scheme:
minima:
  skin: solarized

# Links that appear in the header or footer:
social_links:
  - platform: github
    user_url: "https://github.com/simonlocke"
  - platform: email
    user_url: "mailto:slocke@gradcenter.cuny.edu"
