title: Simon Locke
author: Simon Locke
description: Mathematical physics and learning | PhD student at City University of New York Graduate Center

theme: pages-themes/minima@v0.2.0

# Optional but recommended:
show_excerpts: true

# Use the Solarized color scheme:
minima:
  skin: solarized

# Links that appear in the header or footer:
social_links:
  github: simonlocke
  scholar: [your Google Scholar ID]
  email: [yourname]@[youruniversity].edu
